/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  StButtonType,
} from './components/st-button/st-button';

export namespace Components {
  interface StButton {
    'buttonType'?: StButtonType;
    'label': string;
  }
  interface StPopUp {
    'headline': string;
    'hide': () => Promise<void>;
    'message': string;
    'show': () => Promise<void>;
  }
  interface StTile {}
}

declare global {


  interface HTMLStButtonElement extends Components.StButton, HTMLStencilElement {}
  var HTMLStButtonElement: {
    prototype: HTMLStButtonElement;
    new (): HTMLStButtonElement;
  };

  interface HTMLStPopUpElement extends Components.StPopUp, HTMLStencilElement {}
  var HTMLStPopUpElement: {
    prototype: HTMLStPopUpElement;
    new (): HTMLStPopUpElement;
  };

  interface HTMLStTileElement extends Components.StTile, HTMLStencilElement {}
  var HTMLStTileElement: {
    prototype: HTMLStTileElement;
    new (): HTMLStTileElement;
  };
  interface HTMLElementTagNameMap {
    'st-button': HTMLStButtonElement;
    'st-pop-up': HTMLStPopUpElement;
    'st-tile': HTMLStTileElement;
  }
}

declare namespace LocalJSX {
  interface StButton {
    'buttonType'?: StButtonType;
    'label'?: string;
  }
  interface StPopUp {
    'headline'?: string;
    'message'?: string;
    'onPopUpClose'?: (event: CustomEvent<boolean>) => void;
  }
  interface StTile {}

  interface IntrinsicElements {
    'st-button': StButton;
    'st-pop-up': StPopUp;
    'st-tile': StTile;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'st-button': LocalJSX.StButton & JSXBase.HTMLAttributes<HTMLStButtonElement>;
      'st-pop-up': LocalJSX.StPopUp & JSXBase.HTMLAttributes<HTMLStPopUpElement>;
      'st-tile': LocalJSX.StTile & JSXBase.HTMLAttributes<HTMLStTileElement>;
    }
  }
}


